# Generated by Django 3.1.7 on 2021-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalentryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dr_account', models.CharField(max_length=300)),
                ('dr_price', models.IntegerField()),
                ('dr_class', models.CharField(choices=[('assets', '資産'), ('liabilities', '負債'), ('equity', '純資産'), ('expenses', '費用'), ('revenue', '収益')], max_length=300)),
                ('cr_account', models.CharField(max_length=300)),
                ('cr_price', models.IntegerField()),
                ('cr_class', models.CharField(choices=[('assets', '資産'), ('liabilities', '負債'), ('equity', '純資産'), ('expenses', '費用'), ('revenue', '収益')], max_length=300)),
            ],
        ),
    ]
