# Generated by Django 3.1.5 on 2021-03-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalentryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentrymodel',
            old_name='account',
            new_name='cr_account',
        ),
        migrations.RenameField(
            model_name='journalentrymodel',
            old_name='price',
            new_name='dr_account',
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='cr_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='dr_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
